functionsDirectory = "E:\\1111\\1111\\adhd-website\\netlify\\functions"
functionsDirectoryOrigin = "ui"
headersOrigin = "config"
redirectsOrigin = "config"

[dev]
framework = "#custom"

[functions]

[functions."*"]
node_bundler = "esbuild"

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"
pinned_version = "5"

[plugins.inputs]

[build]
publish = "E:\\1111\\1111\\adhd-website\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "E:\\1111\\1111\\adhd-website\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"
NEXT_TELEMETRY_DISABLED = "1"
NODE_ENV = "production"

[build.processing]
skip_processing = true

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]